import {Gilda_Display} from "next/font/google";
import "./globals.css";

export const glida = Gilda_Display(
  {weight: ['400',], style: "normal",subsets: ["latin-ext"], display: "swap"},
)



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${glida.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
